### ISSUE TITLE
Erro de encoding após a instalação

### ISSUE THREAD

**Issue by agnogueira** [forcontent/idgx.buildout#2]
Após seguir todos os passo para instalção do protal descritos na documentação, encontrei o seguinte erro em alguns momentos durante a edição de conteúdo, como por exemplo ao COMPOR uma capa:

Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 162, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 371, in publish_module
  Module ZPublisher.WSGIPublisher, line 274, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module Products.PDBDebugMode.wsgi_runcall, line 60, in pdb_runcall
  Module collective.cover.browser.compose, line 29, in _call_
  Module Products.Five.browser.pagetemplatefile, line 126, in _call_
  Module Products.Five.browser.pagetemplatefile, line 61, in _call_
  Module zope.pagetemplate.pagetemplate, line 135, in pt_render
  Module Products.PageTemplates.engine, line 378, in _call_
  Module z3c.pt.pagetemplate, line 176, in render
  Module chameleon.zpt.template, line 302, in render
  Module chameleon.template, line 192, in render
  Module 7eb57cd9233032fbfb451df53b8d1b28, line 212, in render
  Module 0d359edf3ceb9bc2b7e767d6a20d674c, line 1257, in render_master
  Module 0d359edf3ceb9bc2b7e767d6a20d674c, line 432, in render_content
  Module 7eb57cd9233032fbfb451df53b8d1b28, line 181, in __fill_main
  Module zope.tales.expressions, line 250, in _call_
  Module Products.PageTemplates.Expressions, line 196, in _eval
  Module Products.PageTemplates.Expressions, line 126, in render
  Module collective.cover.browser.contentchooser, line 43, in _call_
  Module zope.browserpage.viewpagetemplatefile, line 81, in _call_
  Module zope.browserpage.viewpagetemplatefile, line 49, in _call_
  Module zope.pagetemplate.pagetemplate, line 135, in pt_render
  Module Products.PageTemplates.engine, line 378, in _call_
  Module z3c.pt.pagetemplate, line 176, in render
  Module chameleon.zpt.template, line 302, in render
  Module chameleon.template, line 192, in render
  Module 9522ca39d60719f081fc0cdb9ec441ad, line 280, in render
  Module zope.tales.expressions, line 250, in _call_
  Module Products.PageTemplates.Expressions, line 196, in _eval
  Module Products.PageTemplates.Expressions, line 126, in render
  Module collective.cover.browser.contentchooser, line 96, in _call_
  Module collective.cover.browser.contentchooser, line 92, in render
  Module zope.browserpage.viewpagetemplatefile, line 81, in _call_
  Module zope.browserpage.viewpagetemplatefile, line 49, in _call_
  Module zope.pagetemplate.pagetemplate, line 135, in pt_render
  Module Products.PageTemplates.engine, line 378, in _call_
  Module z3c.pt.pagetemplate, line 176, in render
  Module chameleon.zpt.template, line 302, in render
  Module chameleon.template, line 214, in render
  Module chameleon.template, line 192, in render
  Module 5f2756a4854a05a1011907bd3d6a9727, line 414, in render
  Module Products.PageTemplates.Expressions, line 446, in _call_
UnicodeDecodeError: <unprintable UnicodeDecodeError object>

**Comment by agnogueira** [comment]
A solução temporária para o problema é editar o arquivo de configuração do Python 2.7

O arquivo fica normalmente em:
 /usr/lib/python2.7/site.py
 
 Basta alterar o encoding de ascii para utf-8 e salvar o arquivo

**Comment by cleberjsantos** [comment]
Problema resolvido com o uso do parâmetro **initialization**: https://github.com/forcontent/idgx.buildout/commit/dfea2bdaf12befa99ac636990e12e46eda5eb12b
