### ISSUE TITLE
Erro ao Adicionar uma notícia

### ISSUE THREAD

**Issue by joaby12** [forcontent/idgx.buildout#3]
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 162, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 371, in publish_module
  Module ZPublisher.WSGIPublisher, line 274, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module Products.PDBDebugMode.wsgi_runcall, line 60, in pdb_runcall
  Module plone.z3cform.layout, line 63, in __call__
  Module plone.z3cform.layout, line 47, in update
  Module plone.dexterity.browser.add, line 141, in update
  Module plone.z3cform.fieldsets.extensible, line 65, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 145, in update
  Module plone.app.z3cform.csrf, line 22, in execute
  Module z3c.form.action, line 98, in execute
  Module z3c.form.button, line 315, in __call__
  Module z3c.form.button, line 170, in __call__
  Module plone.dexterity.browser.add, line 116, in handleAdd
  Module z3c.form.form, line 263, in createAndAdd
  Module plone.dexterity.browser.add, line 82, in create
  Module plone.dexterity.browser.add, line 200, in _applyChanges
  Module z3c.form.datamanager, line 91, in set
  Module idgx.portal.behaviors.metadata, line 162, in _set_copyright
ValueError: Copyright must be text.

**Comment by cleberjsantos** [comment]
Adicionei no produto correto https://github.com/forcontent/idgx.portal/issues/3
